<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TvTracker.Shared\TvTracker.Shared.csproj" />
    <ProjectReference Include="..\TvTracker.Tmdb\TvTracker.Tmdb.csproj" />
    <ProjectReference Include="..\TvTracker.Data\TvTracker.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
